name: Install yq
description: Installs mikefarah/yq on the runner so that it can be used by subsequent steps.
author: Daniel Weibel
inputs:
  version:
    description: The version of yq to use (by default, the latest version is used).
    default: latest
runs:
  using: composite
  steps:
    - name: determine-version
      run: |
        if [[ "${{ inputs.version }}" = latest ]]; then
          VERSION=$(wget -q -O - "$GITHUB_API_URL"/repos/mikefarah/yq/releases/latest | jq -r .tag_name)
        else
          if ! curl -s "$GITHUB_API_URL"/repos/mikefarah/yq/releases | jq -r '.[].tag_name' | grep -q '^${{ inputs.version }}'; then
            echo -e "Error: ${{ inputs.version }} is not a valid version of yq\nFind available versions on https://github.com/mikefarah/yq/releases"
            exit 1
          else
            VERSION=${{ inputs.version }}
          fi
        fi
        echo "VERSION=$VERSION" >>"$GITHUB_ENV"
      shell: bash
    - name: determine-binary
      run: |
        case "${{ runner.os }}" in
          Linux) BINARY=yq_linux_amd64
          # TODO: test on macOS runner
          #macOS) BINARY=yq_darwin_amd64
        esac
        echo "BINARY=$BINARY" >>"$GITHUB_ENV"
      shell: bash
    - name: install
      run: |
        sudo wget -q -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/"$VERSION"/"$BINARY" &&
        sudo chmod +x /usr/local/bin/yq
      shell: bash
    - name: verify
      run: yq --version
      shell: bash
